name: Compile, Sign, and Deploy Metatrader Installer

on:
  push:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run MetaEditor Compiler
      uses: mhriemers/metatrader-compile@v1.0.1
      with:
        files: 'SimpleEA.mq4'
        version: '4'

  copy-ex4:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout DeployMetatrader repository
      uses: actions/checkout@v2
      with:
        repository: PinkPanther-ny/DeployMetatrader
        token: ${{ secrets.GITHUB_TOKEN }}
        path: DeployMetatrader

    - name: Copy Compiled EX4 to Target Path
      run: |
        mkdir -p "DeployMetatrader/黑金进阶版/eas"
        cp SimpleEA.ex4 "DeployMetatrader/黑金进阶版/eas/Forexman算法交易系统-黑金进阶版.ex4"

  compile-installer:
    runs-on: windows-latest

    steps:
    - name: Checkout DeployMetatrader repository
      uses: actions/checkout@v2
      with:
        repository: PinkPanther-ny/DeployMetatrader
        path: DeployMetatrader

    - name: Run Inno Setup Compiler
      uses: idleberg/innosetup-action@v1
      with:
        script: "DeployMetatrader/黑金进阶版.iss"

  sign-installer:
    runs-on: windows-latest

    steps:
    - name: Sign Installer
      uses: Delphier/SignTool@v1
      with:
        file: "DeployMetatrader/Forexman安装程序_黑金进阶版.exe"
        cert: "D:\\Code\\DeployMetatrader\\Forexman Investments (Shanghai) Ltd.pfx"
        password: ${{ secrets.CERT_PASSWORD }}
        timestamp: "http://timestamp.digicert.com"
        digest_algorithm: "SHA256"
        timestamp_algorithm: "SHA256"

  upload-installer:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: pip install -r requirements.txt

    - name: Upload Installer
      run: |
        python upload.py -p "Forexman算法交易系统 - 黑金进阶版" -f "DeployMetatrader/Forexman安装程序_黑金进阶版.exe"
