name: Compile MQL4

on:
  push:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run MetaEditor Compiler
      uses: mhriemers/metatrader-compile@v1.0.1
      with:
        files: 'SimpleEA.mq4'  # or specify the path if the file is in a different folder
        version: '4'  # MetaTrader version 4 or 5
