name: Compile, Sign, and Deploy Metatrader Installer

on:
  push:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run MetaEditor Compiler
      uses: mhriemers/metatrader-compile@v1.0.1
      with:
        files: 'SimpleEA.mq4'
        version: '4'

    - name: Upload Compiled EX4 as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: compiled-ex4
        path: SimpleEA.ex4

  copy-ex4:
    runs-on: ubuntu-latest
    needs: compile

    steps:
    - name: Clone DeployMetatrader repository
      uses: GuillaumeFalourd/clone-github-repo-action@v2.3
      with:
        owner: PinkPanther-ny
        repository: DeployMetatrader
        branch: 'master'
        access-token: ${{ secrets.DEPLOY_REPO_PAT }}

    - name: Download Compiled EX4 Artifact
      uses: actions/download-artifact@v4
      with:
        name: compiled-ex4

    - name: Copy Compiled EX4 to Target Path
      run: |
        mkdir -p "DeployMetatrader/黑金进阶版/eas"
        cp SimpleEA.ex4 "DeployMetatrader/黑金进阶版/eas/Forexman算法交易系统-黑金进阶版.ex4"

    - name: Upload DeployMetatrader Directory as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: deploymetatrader-dir
        path: DeployMetatrader/

  compile-installer:
    runs-on: windows-latest
    needs: copy-ex4

    steps:
    - name: Download DeployMetatrader Directory Artifact
      uses: actions/download-artifact@v4
      with:
        name: deploymetatrader-dir
        path: "DeployMetatrader"

    - name: Show Current Directory (pwd)
      run: |
        echo "Current Directory:"
        pwd
      shell: powershell

    - name: Run Inno Setup Compiler
      uses: Minionguyjpro/Inno-Setup-Action@v1.2.4
      with:
        path: "DeployMetatrader/黑金进阶版.iss"

    - name: Create Output Directory and Move EXE
      run: |
        mkdir out
        move "DeployMetatrader/Forexman安装程序_黑金进阶版.exe" out/

    - name: Upload Installer EXE as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: installer-exe
        path: out/
    - name: Show Current Directory
      run: |
        echo "Current Directory:"
        pwd
      shell: powershell

  sign-installer:
    runs-on: windows-latest
    needs: compile-installer

    steps:
    - name: Download Installer EXE Artifact
      uses: actions/download-artifact@v4
      with:
        name: installer-exe

    - name: List Files in Current Directory
      run: |
        echo "Files in Current Directory:"
        ls -Recurse
      shell: powershell
  
    - name: Sign Installer EXE
      uses: skymatic/code-sign-action@v1
      with:
        certificate: '${{ secrets.CERTIFICATE }}'
        password: '${{ secrets.PASSWORD }}'
        certificatesha1: '${{ secrets.CERTHASH }}'
        certificatename: '${{ secrets.CERTNAME }}'
        description: 'Forexman Installer'
        timestampUrl: 'http://timestamp.digicert.com'
        folder: '.'
        recursive: false

    - name: Download DeployMetatrader Directory Artifact
      uses: actions/download-artifact@v4
      with:
        name: deploymetatrader-dir
        path: "DeployMetatrader"
  
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install Python dependencies
      run: pip install -r DeployMetatrader/requirements.txt
    
    - name: Run Python Upload Script
      run: |
        python DeployMetatrader/upload.py -p "Forexman算法交易系统 - 黑金进阶版" -f "out/Forexman安装程序_黑金进阶版.exe"
