name: Compile, Sign, and Deploy Metatrader Installer

on:
  push:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run MetaEditor Compiler
      uses: mhriemers/metatrader-compile@v1.0.1
      with:
        files: 'SimpleEA.mq4'
        version: '4'

    - name: Upload Compiled EX4 as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: compiled-ex4
        path: SimpleEA.ex4

  copy-ex4:
    runs-on: ubuntu-latest
    needs: compile

    steps:
    - name: Clone DeployMetatrader repository
      uses: GuillaumeFalourd/clone-github-repo-action@v2.3
      with:
        owner: PinkPanther-ny
        repository: DeployMetatrader
        branch: 'master'
        access-token: ${{ secrets.DEPLOY_REPO_PAT }}

    - name: Download Compiled EX4 Artifact
      uses: actions/download-artifact@v2
      with:
        name: compiled-ex4

    - name: Copy Compiled EX4 to Target Path
      run: |
        mkdir -p "DeployMetatrader/黑金进阶版/eas"
        cp SimpleEA.ex4 "DeployMetatrader/黑金进阶版/eas/Forexman算法交易系统-黑金进阶版.ex4"

    - name: Upload DeployMetatrader Directory as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: deploymetatrader-dir
        path: DeployMetatrader/

  compile-installer:
    runs-on: windows-latest
    needs: copy-ex4

    steps:
    - name: Download DeployMetatrader Directory Artifact
      uses: actions/download-artifact@v2
      with:
        name: deploymetatrader-dir

    - name: Run Inno Setup Compiler
      uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
      with:
        path: "DeployMetatrader/黑金进阶版.iss"
